# .yarnrc.yml
nodeLinker: node-modules        # create node_modules (most libs expect this)
enableGlobalCache: true
checksumBehavior: update
yarnPath: null                  # let Corepack manage Yarn (no .yarn/releases needed)
